# Remark : last updated : 240827
#plugin_outlet:
  #default: "above-site-header"
  #type: string 
plugin_outlet:
  default: "above-main-container"
  type: enum
  choices:
    - above-main-container
enable_debug_for_user_ids:   
  type: list
  default: "2|42"
  list_type: simple
  regex: "^\\d+$"
  description: "Enable debug for specific users by numeric ID"
enable_debug_for_admins:
  type: bool
  default: true
  description: ""
enable_debug_for_all:
  type: bool
  default: false
  description: ""
enable_modal_only_for_admins:
  type: bool
  default: true
  description: "disable to make this component visible to Non Admins (All users)"
enable_modal_footer_internal_debug:
  type: bool
  default: false
  description: "enable for debug info in the modal footer (seen only by admins)"
button_style:
  type: enum
  default: btn-primary
  choices:
    - btn-default
  description: "btn-primary is a blue (tertiary). btn-default is a grey (primary-low)."
enable_email_notifications_check_box:
  type: bool
  default: false
  description: "Enable to show Email Notifications checkbox in Step 3 of modal"
#button_icon:
  #type: string
  #default: "user"
  #description: "Add icon to Log In button. (FontAwesome 5 icons)"
#custom_image:
  #type: upload
  #default: ""
  #description: "Upload an image"
#custom_image_width:
  #type: string
  #default: "auto"
  #description: "The uploaded image width. You can use px, % etc, e.g. 100% will add a full modal width (minus padding) image."
#custom_image_position:
  #default: center
  #type: enum
  #choices:
    #- left
    #- right
  #description: "Custom image position."
