plugin_outlet:
  default: "above-site-header"
  type: string 
enable_debug_for_admins:
  type: bool
  default: true
  description: ""
enable_debug_for_all:
  type: bool
  default: false
  description: ""
enable_modal_only_for_admins:
  type: bool
  default: true
  description: "disable to make this component visible to Non Admins (All users)"
enable_modal_footer_internal_debug:
  type: bool
  default: false
  description: "enable for debug info in the modal footer (seen only by admins)"
button_style:
  type: enum
  default: btn-primary
  choices:
    - btn-default
  description: "btn-primary is a blue (tertiary). btn-default is a grey (primary-low)."
svg_icons: 
  default: 'house|tv|landmark'
  type: 'list'
  list_type: 'compact'
  description: "Register additional Icons from Font Awesome 5 free library"
#button_icon:
  #type: string
  #default: "user"
  #description: "Add icon to Log In button. (FontAwesome 5 icons)"
#custom_image:
  #type: upload
  #default: ""
  #description: "Upload an image"
#custom_image_width:
  #type: string
  #default: "auto"
  #description: "The uploaded image width. You can use px, % etc, e.g. 100% will add a full modal width (minus padding) image."
#custom_image_position:
  #default: center
  #type: enum
  #choices:
    #- left
    #- right
  #description: "Custom image position."
